"""Stable, ordered L3 feature contract. JSON null means unavailable."""

SCHEMA = "agent-fingerprint-browser-features/v5"
FEATURE_NAMES = (
    'paste_count',
    'mouse_curvature_angle_range',
    'hold_latency_median',
    'inter_key_latency_median',
    'hold_latency_mean',
    'scroll_distance_std',
    'change_count',
    'scroll_distance_mean',
    'scroll_time_median',
    'input_count',
    'mouse_event_count',
    'scroll_distance_range',
    'button0_count',
    'hold_latency_range',
    'inter_key_latency_mean',
    'scroll_time_mean',
    'scroll_distance_median',
    'mouse_curvature_angle_mean',
    'dangling_keydown',
    'scroll_time_std',
    'scroll_count',
    'mouse_direction_mean',
    'inter_key_latency_range',
    'button0_down_up_ratio',
    'mouse_curvature_angle_std',
    'mouse_curvature_distance_median',
    'mouse_direction_range',
    'scroll_time_range',
    'hold_latency_std',
    'scrollend_count',
    'inter_key_latency_std',
    'backspace_delete_count',
    'mouse_curvature_distance_mean',
    'mousemove_count',
    'keypress_count',
    'mouse_direction_std',
    'dangling_keyup',
    'backspace_delete_ratio',
    'button1_count',
    'button1_down_up_ratio',
    'button2_count',
    'button2_down_up_ratio',
    'button3_count',
    'button3_down_up_ratio',
    'button4_count',
    'button4_down_up_ratio',
    'mouse_direction_median',
    'mouse_curvature_angle_median',
    'mouse_curvature_distance_range',
    'mouse_curvature_distance_std',
    'scroll_reversals',
    'structural_key_ratio',
    'click_x_std',
    'click_y_std',
    'click_bbox_area_frac',
    'link_click_ratio',
    'nav_to_click_ratio',
    'mean_exit_scroll_pct',
    'mouse_transition_distance_mean',
    'mouse_transition_distance_std',
    'mouse_transition_direction_mean',
    'mouse_transition_direction_std',
    'mouse_transition_turn_angle_mean',
    'mouse_transition_turn_angle_std',
    'mouse_transition_interval_mean',
    'mouse_transition_interval_std',
    'mouse_isolated_move_ratio',
)
EPISODE_FEATURE_NAMES = (
    'n_clicks', 'n_navigations', 'n_focus', 'n_events_total', 'page_count',
    'n_unique_domains', 'total_duration_s', 't_first_action_ms', 'mean_iei_ms',
    'std_iei_ms', 'median_iei_ms', 'p10_iei_ms', 'p90_iei_ms', 'iei_trend',
    'mean_click_iei_ms', 'std_click_iei_ms', 'mean_nav_iei_ms', 'std_nav_iei_ms',
    'max_page_dwell_ms', 'mean_key_iei_ms', 'std_key_iei_ms', 'max_scroll_pct',
    'mean_scroll_pct', 'n_deep_scrolls', 'click_top_frac', 'n_link_clicks',
    'popstate_ratio', 'scroll_to_click_ratio', 'actions_per_page',
    'keydowns_per_page', 'focus_per_page',
)
FEATURE_NAMES += EPISODE_FEATURE_NAMES
FEATURE_COUNT = len(FEATURE_NAMES)
